![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

<img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on!

In [1]:
import sys
import numpy as np

## Basic Numpy Arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a[0], a[1] #We can call items like lists

(1, 2)

In [7]:
a[1:] #And also we can use  slicing method of list.

array([2, 3, 4])

In [8]:
a[1:3]

array([2, 3])

In [9]:
a[1:-1]

array([2, 3])

In [10]:
a[::2]

array([1, 3])

In [11]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [12]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [ ]:
b[[0, 2, -1]] #But differently we can call multiple items at once.

array([0., 1., 2.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Types

In [13]:
a

array([1, 2, 3, 4])

In [14]:
a.dtype

dtype('int64')

In [15]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
b.dtype

dtype('float64')

In [18]:
a= np.array([1, 2, 3, 4])

In [19]:
a.astype('float64') #Because of the version differences to change data type, you need to use astype() method.

array([1., 2., 3., 4.])

In [20]:
a.astype('int8')

array([1, 2, 3, 4], dtype=int8)

In [21]:
c = np.array(['a', 'b', 'c'])

In [22]:
c.dtype

dtype('<U1')

In [23]:
d = np.array([{'a': 1}, sys])

In [24]:
d.dtype

dtype('O')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Dimensions and shapes

In [25]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [26]:
A.shape

(2, 3)

In [29]:
A.ndim #width and length

2

In [28]:
A.size #Number of element.

6

In [30]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [31]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [32]:
B.shape

(2, 2, 3)

In [33]:
B.ndim

3

In [34]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [36]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
]) #If there is no math in sizes,there will be no arrays

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [37]:
C.dtype

NameError: name 'C' is not defined

In [ ]:
C.shape

(2,)

In [ ]:
C.size

2

In [ ]:
type(C[0])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Indexing and Slicing of Matrices

In [38]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [39]:
A[1]

array([4, 5, 6])

In [40]:
A[1][0]

4

In [ ]:
# A[d1, d2, d3, d4]

In [41]:
A[1, 0]

4

In [45]:
A[0:2] #First row to second row.

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
A[:, :2] #(rows,coloumn)

array([[1, 2],
       [4, 5],
       [7, 8]])

In [52]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [59]:
A[:, 2:]

array([[3],
       [6],
       [9]])

In [60]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
A[1] = np.array([10, 10, 10]) #To assign numbers on second row. You just write by writng index number.

In [62]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [64]:
A[2] = 99 #Also repititive numbers can be assigned to third row by this method.

In [65]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Summary statistics

In [66]:
a = np.array([1, 2, 3, 4])

In [67]:
a.sum()

10

In [68]:
a.mean()

2.5

In [69]:
a.std()

1.118033988749895

In [70]:
a.var()

1.25

In [71]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [72]:
A.sum()

45

In [73]:
A.mean()

5.0

In [74]:
A.std()

2.581988897471611

In [76]:
A.sum(axis=0) #axis=0 means coloumn

array([12, 15, 18])

In [77]:
A.sum(axis=1) #axis=1 means rows

array([ 6, 15, 24])

In [78]:
A.mean(axis=0)

array([4., 5., 6.])

In [79]:
A.mean(axis=1)

array([2., 5., 8.])

In [80]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [81]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Broadcasting and Vectorized operations

In [82]:
a = np.arange(4) #Arrange metho create an array till the given value.

In [83]:
a

array([0, 1, 2, 3])

In [85]:
a + 10 #Each array added with selected value

array([10, 11, 12, 13])

In [86]:
a * 10

array([ 0, 10, 20, 30])

In [87]:
a

array([0, 1, 2, 3])

In [88]:
a += 100

In [89]:
a

array([100, 101, 102, 103])

In [90]:
l = [0, 1, 2, 3]

In [92]:
[i * 10 for i in l] # we can divide this comprehension into 2: first part is desired operation in each iteration that happend,second phrase is loops

[0, 10, 20, 30]

In [93]:
a = np.arange(4)

In [94]:
a

array([0, 1, 2, 3])

In [95]:
b = np.array([10, 10, 10, 10])

In [96]:
a + b

array([10, 11, 12, 13])

In [97]:
a * b

array([ 0, 10, 20, 30])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Boolean arrays
_(Also called masks)_

In [98]:
a = np.arange(4)

In [99]:
a

array([0, 1, 2, 3])

In [100]:
a[[0, -1]]

array([0, 3])

In [101]:
a[[True, False, False, True]] #We can select items by booleans

array([0, 3])

In [102]:
a >= 2

array([False, False,  True,  True])

In [103]:
a[a >= 2]

array([2, 3])

In [104]:
a.mean()

1.5

In [105]:
a[a > a.mean()]

array([2, 3])

In [106]:
a[~(a > a.mean())]

array([0, 1])

In [ ]:
a[(a == 0) | (a == 1)]

In [ ]:
a[(a <= 2) & (a % 2 == 0)]

In [ ]:
A = np.random.randint(100, size=(3, 3))

In [ ]:
A

In [ ]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

In [ ]:
A > 30

In [ ]:
A[A > 30]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Linear Algebra

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [ ]:
A.dot(B)

In [ ]:
A @ B

In [ ]:
B.T

In [ ]:
A

In [ ]:
B.T @ A

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Size of objects in Memory

### Int, floats

In [ ]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

In [ ]:
# Longs are even larger
sys.getsizeof(10**100)

In [ ]:
# Numpy size is much smaller
np.dtype(int).itemsize

In [ ]:
np.dtype(float).itemsize

### Lists are even larger

In [ ]:
# A one-element list
sys.getsizeof([1])

In [ ]:
# An array of one element in numpy
np.array([1]).nbytes

### And performance is also important

In [ ]:
l = list(range(1000))

In [ ]:
a = np.arange(1000)

In [ ]:
%time np.sum(a ** 2)

In [ ]:
%time sum([x ** 2 for x in l])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Useful Numpy functions

### `random`

In [ ]:
np.random.random(size=2)

In [ ]:
np.random.normal(size=2)

In [ ]:
np.random.rand(2, 4)

---
### `arange`

In [ ]:
np.arange(10)

In [ ]:
np.arange(5, 10)

In [ ]:
np.arange(0, 1, .1)

---
### `reshape`

In [ ]:
np.arange(10).reshape(2, 5)

In [ ]:
np.arange(10).reshape(5, 2)

---
### `linspace`

In [ ]:
np.linspace(0, 1, 5)

In [ ]:
np.linspace(0, 1, 20)

In [ ]:
np.linspace(0, 1, 20, False)

---
### `zeros`, `ones`, `empty`

In [ ]:
np.zeros(5)

In [ ]:
np.zeros((3, 3))

In [ ]:
np.zeros((3, 3), dtype=np.int)

In [ ]:
np.ones(5)

In [ ]:
np.ones((3, 3))

In [ ]:
np.empty(5)

In [ ]:
np.empty((2, 2))

---
### `identity` and `eye`

In [ ]:
np.identity(3)

In [ ]:
np.eye(3, 3)

In [ ]:
np.eye(8, 4)

In [ ]:
np.eye(8, 4, k=1)

In [ ]:
np.eye(8, 4, k=-3)

In [ ]:
"Hello World"[6]

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)